version: 2
updates:
- package-ecosystem: cargo
  directory: "/frb_codegen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frb_rust"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frb_example/frb_example_rust"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
