# https://mergeable.readthedocs.io/en/latest/recipes.html#recipes-page
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Approval check & merge when pass all checks"
    validate:
      - do: approvals
        min:
          count: 1
    pass:
      - do: merge
        merge_method: "merge"
