# https://github.com/marketplace/actions/repo-file-sync-action
fzyzcjy/flutter_rust_bridge:
  - source: README.md
    dest: docs/index.md
  - source: README.md
    dest: frb_rust/README.md
  - source: README.md
    dest: frb_codegen/README.md
  - source: README.md
    dest: frb_dart/README.md

  - source: CHANGELOG.md
    dest: frb_dart/CHANGELOG.md
