[package]
name = "flutter_rust_bridge"
version = "0.1.0"
edition = "2018"
description = "High-level memory-safe bindgen for Dart/Flutter <-> Rust"
license = "MIT"
repository = "https://github.com/fzyzcjy/flutter_rust_bridge"

[dependencies]
allo-isolate = "0.1.10"
anyhow = "1.0.44"
threadpool = "1.8.1"
lazy_static = "1.4.0"
parking_lot = "0.11.2"
