[package]
name = "flutter_rust_bridge"
version = "1.38.0"
edition = "2018"
description = "High-level memory-safe binding generator for Flutter/Dart <-> Rust"
license = "MIT"
repository = "https://github.com/fzyzcjy/flutter_rust_bridge"
keywords = ["flutter", "dart", "ffi", "code-generation", "bindings"]
categories = ["development-tools::ffi"]

[dependencies]
anyhow = "1.0.58"
flutter_rust_bridge_macros = { path = "../frb_macros", version = "1" }
lazy_static = { version = "1.4.0" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
allo-isolate = { version = "0.1.13-beta.5" }
parking_lot = { version = "0.12.1" }
threadpool = { version = "1.8.1" }

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = { version = "0.1.7" }
wasm-bindgen = { version = "0.2.81" }
js-sys = { version = "0.3.58" }
web-sys = { version = "0.3.58", features = [
    "DedicatedWorkerGlobalScope",
    "MessageEvent",
    "MessagePort",
    "ErrorEvent",
    "Event",
    "Blob",
    "BlobPropertyBag",
    "Worker",
    "Url",
] }

[build-dependencies]
build-target = "0.4.0"
