[package]
name = "flutter_rust_bridge"
version = "1.8.0"
edition = "2018"
description = "High-level memory-safe binding generator for Flutter/Dart <-> Rust"
license = "MIT"
repository = "https://github.com/fzyzcjy/flutter_rust_bridge"
keywords = ["flutter", "dart", "ffi", "code-generation", "bindings"]
categories = ["development-tools::ffi"]

[dependencies]
allo-isolate = "0.1.11"
#allo-isolate = { git = "https://github.com/fzyzcjy/allo-isolate" } # hack, until upstream PR is merged and released
anyhow = "1.0.50"
threadpool = "1.8.1"
lazy_static = "1.4.0"
parking_lot = "0.11.2"
