name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 1.41.1
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  args: ^2.3.1
  fixnum: ^1.0.1
  js: ^0.6.4
  meta: ^1.3.0
  path: any
  puppeteer: ^2.12.0
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0
dev_dependencies:
  lints: ">=1.0.1 <3.0.0"
  test: ^1.16.8
executables:
  flutter_rust_bridge_serve: bin/serve.dart
