name: flutter_rust_bridge
description: High-level memory-safe bindgen for Dart/Flutter <-> Rust
version: 1.0.0
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.3.0
  lints: ^1.0.1
dev_dependencies:
  test: ^1.16.8
