name: Codegen
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: macos-latest
            family: osx
          - image: windows-latest
            family: windows
          - image: ubuntu-latest
            family: linux

    runs-on: ${{ matrix.os.image }}

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dart global dependency
        run: dart pub global activate ffigen

      # needed by `ffigen`, see https://github.com/dart-lang/ffigen#installing-llvm
      - name: Install llvm dependency (Linux)
        if: ${{ matrix.os.family == 'linux' }}
        run: sudo apt-get install -y libclang-dev

      # NOTE in windows, need "\\" instead of "/"
      - name: Run codegen to pure_dart example (non-windows)
        if: ${{ matrix.os.family != 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen -- --rust-input ../frb_example/pure_dart/rust/src/api.rs --dart-output ../frb_example/pure_dart/dart/lib/bridge_generated.dart --dart-format-line-length 120
        env:
          RUST_LOG: debug
      - name: Run codegen to pure_dart example (windows)
        if: ${{ matrix.os.family == 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen -- --rust-input ..\\frb_example\\pure_dart\\rust\\src\\api.rs --dart-output ..\\frb_example\\pure_dart\\dart\\lib\\bridge_generated.dart --dart-format-line-length 120
        env:
          RUST_LOG: debug

      - name: Run codegen to with_flutter example (non-windows)
        if: ${{ matrix.os.family != 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen -- --rust-input ../frb_example/with_flutter/rust/src/api.rs --dart-output ../frb_example/with_flutter/lib/bridge_generated.dart --c-output ../frb_example/with_flutter/ios/Runner/bridge_generated.h --dart-format-line-length 120
        env:
          RUST_LOG: debug
      - name: Run codegen to with_flutter example (windows)
        if: ${{ matrix.os.family == 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen -- --rust-input ..\\frb_example\\with_flutter\\rust\\src\\api.rs --dart-output ..\\frb_example\\with_flutter\\lib\\bridge_generated.dart --c-output ..\\frb_example\\with_flutter\\ios\\Runner\\bridge_generated.h --dart-format-line-length 120
        env:
          RUST_LOG: debug

      - name: 'Check no code change (If fail: Please ensure you have run codegen on examples and commit those changes!)'
        run: git diff --exit-code
