name: Lints

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  combo:
    name: Clippy + rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Run fmt for codegen
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=./frb_codegen/Cargo.toml --all -- --check
      - name: Run clippy for codegen
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=./frb_codegen/Cargo.toml -- -D warnings

      - name: Run fmt for rust runtime
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=./frb_rust/Cargo.toml --all -- --check
      - name: Run clippy for rust runtime
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=./frb_rust/Cargo.toml -- -D warnings

      - name: Run fmt for example
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=./frb_example/frb_example_rust/Cargo.toml --all -- --check
      - name: Run clippy for example
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=./frb_example/frb_example_rust/Cargo.toml -- -D warnings
