name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build codegen
      working-directory: ./frb_codegen
      run: cargo build --verbose
    - name: Run tests for codegen
      working-directory: ./frb_codegen
      run: cargo test --verbose

    - name: Run codegen to frb_example/simple
      working-directory: ./frb_codegen
      run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen ../frb_example/simple/rust/flutter_rust_bridge.yaml

    - name: 'Check no code change (If fail: Please ensure you have run codegen on examples and commit those changes!)'
      run: git diff --exit-code

    - name: Build rust runtime
      working-directory: ./frb_rust
      run: cargo build --verbose
    - name: Run tests for rust runtime
      working-directory: ./frb_rust
      run: cargo test --verbose

    - name: Build example
      working-directory: ./frb_example/simple/rust
      run: cargo build --verbose
    - name: Run tests for example
      working-directory: ./frb_example/simple/rust
      run: cargo test --verbose
